repos:
  - repo: local
    hooks:
      - id: clear-notebook-outputs
        name: Clear Jupyter Notebook outputs
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        language: system
        types: [jupyter]
