repos:
  - repo: local
    hooks:
      - id: clear-notebook-outputs
        name: Clear Jupyter Notebook outputs
        entry: bash -c 'jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "$@" && git add "$@"'
        language: system
        types: [jupyter]
